version: '3.8'

services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
    environment:
      - YTDL_OPTIONS: {"format": "best"}

  metube-gateway:
    image: nginx:alpine
    container_name: metube-gateway
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./gateway-simple.conf:/etc/nginx/conf.d/default.conf
      - ./validation-page.html:/usr/share/nginx/html/validation-page.html
    depends_on:
      - metube 