version: '3.8'

services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /volume1/docker/metube/downloads:/downloads
    environment:
      YTDL_OPTIONS: '{"format": "best"}'
    networks:
      - metube-network

  metube-gateway:
    image: nginx:alpine
    container_name: metube-gateway
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - /volume1/docker/metube/gateway-production.conf:/etc/nginx/conf.d/default.conf
      - /volume1/docker/metube/validation-page.html:/usr/share/nginx/html/validation-page.html
      - /volume1/docker/metube/auth-success.html:/usr/share/nginx/html/auth-success.html
      - /volume1/docker/metube/auth-error.html:/usr/share/nginx/html/auth-error.html
    depends_on:
      - metube
    networks:
      - metube-network

networks:
  metube-network:
    driver: bridge 