version: '3.8'

services:
  # Traefik - Reverse Proxy avec authentification automatique
  traefik:
    image: traefik:v2.10
    container_name: traefik-auth-gateway
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@domain.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./middleware-auth.yml:/etc/traefik/middleware-auth.yml:ro
    networks:
      - auth-network
    restart: unless-stopped

  # Service d'authentification automatique
  auth-service:
    image: python:3.9-alpine
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./auth-service.py:/app/auth-service.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - AUTH_SECRET=your-secret-key-change-this
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=Rasulova75
      - AUTH_HEADER=X-Auto-Auth
    command: >
      sh -c "pip install -r requirements.txt && python auth-service.py"
    networks:
      - auth-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.regispailler.fr`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"

  # Stable Diffusion avec authentification automatique
  stablediffusion:
    image: your-stablediffusion-image:latest
    container_name: stablediffusion-auth
    environment:
      - AUTO_AUTH_ENABLED=true
      - AUTO_AUTH_USERNAME=admin
      - AUTO_AUTH_PASSWORD=Rasulova75
      - AUTO_AUTH_SECRET=your-secret-key-change-this
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    networks:
      - auth-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sd.rule=Host(`stablediffusion.regispailler.fr`)"
      - "traefik.http.routers.sd.entrypoints=web"
      - "traefik.http.routers.sd.middlewares=sd-auth"
      - "traefik.http.services.sd.loadbalancer.server.port=7860"
      - "traefik.http.middlewares.sd-auth.headers.customrequestheaders.X-Auto-Auth=your-secret-key-change-this"
      - "traefik.http.middlewares.sd-auth.headers.customrequestheaders.Authorization=Basic YWRtaW46UmFzdWxvdmE3NQ=="

  # IA Tube avec authentification automatique
  iatube:
    image: your-iatube-image:latest
    container_name: iatube-auth
    environment:
      - AUTO_AUTH_ENABLED=true
      - AUTO_AUTH_USERNAME=admin
      - AUTO_AUTH_PASSWORD=Rasulova75
      - AUTO_AUTH_SECRET=your-secret-key-change-this
    networks:
      - auth-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it.rule=Host(`iatube.regispailler.fr`)"
      - "traefik.http.routers.it.entrypoints=web"
      - "traefik.http.routers.it.middlewares=it-auth"
      - "traefik.http.services.it.loadbalancer.server.port=7860"
      - "traefik.http.middlewares.it-auth.headers.customrequestheaders.X-Auto-Auth=your-secret-key-change-this"
      - "traefik.http.middlewares.it-auth.headers.customrequestheaders.Authorization=Basic YWRtaW46UmFzdWxvdmE3NQ=="

  # IA Metube avec authentification automatique
  iametube:
    image: your-iametube-image:latest
    container_name: iametube-auth
    environment:
      - AUTO_AUTH_ENABLED=true
      - AUTO_AUTH_USERNAME=admin
      - AUTO_AUTH_PASSWORD=Rasulova75
      - AUTO_AUTH_SECRET=your-secret-key-change-this
    networks:
      - auth-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.im.rule=Host(`iametube.regispailler.fr`)"
      - "traefik.http.routers.im.entrypoints=web"
      - "traefik.http.routers.im.middlewares=im-auth"
      - "traefik.http.services.im.loadbalancer.server.port=7860"
      - "traefik.http.middlewares.im-auth.headers.customrequestheaders.X-Auto-Auth=your-secret-key-change-this"
      - "traefik.http.middlewares.im-auth.headers.customrequestheaders.Authorization=Basic YWRtaW46UmFzdWxvdmE3NQ=="

networks:
  auth-network:
    driver: bridge 